[bot]
adapters = ["alicebot.adapter.mirai"]
plugin_dirs = ["plugins"]

[adapter.cqhttp]
# 这里是 CQHTTP 适配器的配置
adapter_type = "ws"
host = "127.0.0.1"
port = 6700
url = ""

[adapter.mirai]
adapter_type = "ws"
verify_key = "1234567890"
port = 7701
qq = 3490109344


#[adapter.mirai]
#adapter_type = "reverse-ws"
#verify_key = "1234567890"
#port = 7702
#qq = 3490109344